version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./deployment_sample/nginx:/etc/nginx
    depends_on:
      - medallion

  nginx_proxy:
    image: nginx
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - ./deployment_sample/nginx_proxy:/etc/nginx
    depends_on:
      - nginx

  taxii_integration:
    image: taxii_integration
    restart: unless-stopped
    volumes:
      - ./queries.json:/code/queries.json
    env_file: .env
    depends_on:
      - nginx_proxy
      - redis

  medallion:
    image: ocddev/cti-taxii-server
    container_name: medallion-deployment-sample
    restart: unless-stopped
    command: "uwsgi --ini /deployment_sample/uwsgi.ini"
    volumes:
      - ./medaillon_config.json:/opt/taxii/config.json
      - ./deployment_sample/uwsgi.ini:/deployment_sample/uwsgi.ini
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
#    volumes:
#      - /path/to/mongo_data:/data/db

  redis:
    image: redis:6
    command: redis-server --appendonly yes
    restart: unless-stopped
#    volumes:
#      - /path/to/redis_data:/data
#    network_mode: host
