version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./deployment_sample/nginx:/etc/nginx
    depends_on:
      - medallion

  nginx_proxy:
    image: nginx
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - ./deployment_sample/nginx_proxy:/etc/nginx
      - ./deployment_sample/certs:/etc/certs # Auto signed certs by default
    depends_on:
      - nginx
    networks:
      default:
        aliases:
          - my.taxii_server.com

  taxii_integration:
    build: .
    restart: unless-stopped
    container_name: taxii_integration
    volumes:
      - ./queries.json:/code/queries.json
      - data_volume:/code/output
    env_file: .env
    depends_on:
      - nginx_proxy

  medallion:
    image: ocddev/cti-taxii-server
    container_name: medallion-deployment-sample
    restart: unless-stopped
    command: "uwsgi --ini /deployment_sample/uwsgi.ini"
    volumes:
      - ./medallion_config.json:/opt/taxii/config.json
      - ./deployment_sample/uwsgi.ini:/deployment_sample/uwsgi.ini
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  data_volume:


networks:
  default:
    driver: bridge
